# Generated by Django 3.2.9 on 2021-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to='variants/', verbose_name='Imagen'),
        ),
    ]
