# Generated by Django 3.2.9 on 2021-11-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='Imagen'),
        ),
    ]
